services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build: .
    command: celery -A app.tasks.celery worker --loglevel=info --pool=solo
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
